### PR TITLE
fix: Workaround for "Ignoring invalid configuration option passed to Connection: driver"

### PR DESCRIPTION
**Pull request by ali28729**
Workaround for the warning in #33 .

### CODE REVIEW

**Comment by craig552uk** [comment]
Could someone push this through? This error is a pest.

**Comment by ali28729** [comment]
> Could someone push this through? This error is a pest.

Yeeah, I think this repo is dead. No activity for almost half a year.

**Comment by wzrdtales** [comment]
the mysql driver could use another maintainer agreed :)

**Comment by wzrdtales** [comment]
your implementation is however manipulating the source object which is not just a bad practice but would be problematic in that case. Please clone the config and then delete the property from it.

**Comment by wzrdtales** [comment]
source object may not be manipulated. as stated before, a `JSON.parse(JSON.stringify())` would be appropriate in this case

**Pull request closed without merging**
