### PR TITLE
fix(escaping): escape ' in column comments

### PR DESCRIPTION
**Pull request by williamdes**
fix(escaping): escape ' in column comments

`UNIQUE COMMENT 'Identifiant unique d'établissement'`

`ER_PARSE_ERROR: You have an error in your SQL syntax;`

Added in #15

### CODE REVIEW

**Comment by williamdes** [comment]
@wzrdtales I also added an improvement for TravisCI config

```
 Build config validation 
   root: deprecated key sudo (The key `sudo` has no effect anymore.)
   root: deprecated key sudo (The key `sudo` has no effect anymore.)
   notifications.webhooks.on_start: value false is an alias for never, using never
   notifications.webhooks.on_start: value false is an alias for never, using never
   root: key matrix is an alias for jobs, using jobs
   root: key matrix is an alias for jobs, using jobs
   root: missing dist, using the default xenial
```

Travis CI: https://travis-ci.com/github/williamdes/mysql/builds/155244665

**Comment by williamdes** [comment]
@wzrdtales Did you have some time to review this PR ?

**Comment by williamdes** [comment]
:ping_pong:

**Comment by williamdes** [comment]
@wzrdtales Could you please merge my work ?

**Comment by williamdes** [comment]
:ping_pong: dead project ?

**Comment by williamdes** [comment]
Byeeeeee
Knex JS is better.

**Comment by wzrdtales** [comment]
bye

**Comment by williamdes** [comment]
Seriously why did you not respond @wzrdtales ?

**Comment by williamdes** [comment]
I took time to do the commit, test, and fix..

**Comment by wzrdtales** [comment]
I am not due you anything. I am grateful for any help, but I have work and a lot of it besides open source. I have no obligation whatsoever to answer anyone, I did not sign any SLA with you or your company and you don't pay me the money for that. If it is possible and doesn't gets lost under the other around 300 mails I get per day I do answer. You just had bad luck that I was seeing your mail incoming unlike the ones before which I did not see.

The scene you're making here for such a small change is just inappropriate "I took time to do the commit, test, and fix..", I don't mind when people bug me to raise my attention, I know things get lost under the radar and as said I welcome any help and would also welcome additional maintainers. This toxic attitude of yours is unfortunately common in open source that you're showing and I can just ask you to think about yourself and educate yourself, before you end up being shamed publicly (https://twitter.com/tjholowaychuk/status/1257650926384488448).

**Comment by williamdes** [comment]
Good projects have maintainers how care about contributors, even if the response is months later.

You only show that you do not care about other people spending time on your project.

I get a lot of emails too, and do my best to respond. When people ping pong me I try to do a nice answer that I will have an eye one it one day.

Nobody was obligations, but be nice. Time is a resource you will never get back.

"This toxic attitude of yours" shame one you.

**Comment by wzrdtales** [comment]
yes, bye.

**Pull request closed without merging**
